# 배열(1)

In [5]:
import numpy as np

In [258]:
a = np.array([[0,1,2,3],[5,6,7,8]])

In [259]:
print(a.shape)
print(a.size)
print(a.dtype)
print(a.ndim)

(2, 4)
8
int32
2


In [20]:
a = np.array([0,1,2,3], dtype = 'float')
a

array([0., 1., 2., 3.])

In [26]:
#float는 16bit(2byte)까지 int는 8bit(1byte)까지 가능
a = np.array([0,1,2,3], dtype = 'float16')
a

array([0., 1., 2., 3.], dtype=float16)

In [207]:
li1 = list(range(100))
li2 = list(range(100))

def add_list():
    li3 = []
    for i in range(100):
        li3.append(li1[i] + li2[i])
    return li3

add_list()


[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198]

In [208]:
ar1 = np.array(range(100))
ar2 = np.array(range(100))

def add_array():
    ar3 = ar1 + ar2   
    return ar3

add_array()

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

In [210]:
#python과 numpy 계산속도 비교
import timeit
print(timeit.timeit(add_list, number = 10000))
print(timeit.timeit(add_array, number = 10000))

0.07456220000312896
0.004574799997499213


In [119]:
#2차원 배열
np.array([[1,2,3,4], [5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [122]:
#numpy의 range 사용법
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
#2행 5열 (y, x)
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [131]:
#행만 잡아둔뒤 열 자리에 -1하면 알아서 잡아준다
np.arange(12).reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [212]:
#3차원 배열: 2층 3행 4열(z, y, x)
np.arange(30).reshape(2,5,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

- 두 배열을 연산 할때 주의할 점<br>
: 하나일때를 제외하고, 두배열의 열과 행의 갯수가 같아야 한다

In [10]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [8]:
a + b

array([[ 6,  8],
       [10, 12]])

In [224]:
#위와 같다
np.add(a,b)

array([[ 6,  8],
       [10, 12]])

In [226]:
a * b

array([[ 5, 12],
       [21, 32]])

In [227]:
#위와 같다
np.multiply(a,b)

array([[ 5, 12],
       [21, 32]])

In [9]:
c = np.array([5])
a + c

array([[6, 7],
       [8, 9]])

In [229]:
#위와 같다
a + 5

array([[6, 7],
       [8, 9]])

In [11]:
# 2차원 배열 slicing
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
#5번째 행의 모든 열
a[4,:]

array([20, 21, 22, 23, 24])

In [13]:
#2번째 행의 첫번째, 두번째 열
a[1,(0,2)]

array([5, 7])

In [15]:
#모든 행의 두번째 열
a[:,1]

array([ 1,  6, 11, 16, 21])

# 배열(2)

In [1]:
import numpy as np

In [6]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])

In [13]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [357]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
#sparse matrix (희소행렬)
a = np.zeros((10,10))
a[3,3] = 1
a[5,6] = 1
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
np.ones((10,10))*3

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [239]:
#정사각 행렬
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [242]:
#직사각 행렬
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [246]:
#full
np.full((3,2),5)

array([[5, 5],
       [5, 5],
       [5, 5]])

In [249]:
import copy
a = np.array([1,2,3,4])
b = copy.copy(a)

b[0] = 100

print(a,b)

[1 2 3 4] [100   2   3   4]


In [278]:
#stack: FILO(First In Last Out) 선착순의 반대
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[7,8],[9,10],[11,12]])

In [279]:
#vstack(): 수직 방향으로 붙힌다, 열의 갯수는 변하지 않는다
np.vstack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [280]:
#hstack(): 수평 방향으로 붙힌다, 행의 갯수는 변하지 않는다
np.hstack((a,b))

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

In [269]:
#dstack(): 열의 갯수가 행의 갯수가 되고 행의 갯수가 층의 갯수가 된다
np.dstack((a,b))

array([[[ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10]],

       [[ 5, 11],
        [ 6, 12]]])

In [272]:
a = np.arange(32).reshape(4,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [275]:
#vsplit(): 수직 방향으로 찢는다
np.vsplit(a,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]])]

In [68]:
np.vsplit(a,4)

[array([[0, 1, 2, 3, 4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11, 12, 13, 14, 15]]),
 array([[16, 17, 18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29, 30, 31]])]

In [274]:
#hsplit(): 수평 방향으로 찢는다
np.hsplit(a, 2)

[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19],
        [24, 25, 26, 27]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31]])]

In [63]:
np.hsplit(a,4)

[array([[ 0,  1],
        [ 8,  9],
        [16, 17],
        [24, 25]]),
 array([[ 2,  3],
        [10, 11],
        [18, 19],
        [26, 27]]),
 array([[ 4,  5],
        [12, 13],
        [20, 21],
        [28, 29]]),
 array([[ 6,  7],
        [14, 15],
        [22, 23],
        [30, 31]])]

In [289]:
a = np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [290]:
a.shape

(3, 2)

In [291]:
a.flatten()

array([0, 1, 2, 3, 4, 5])

In [293]:
#행과 열의 갯수가 바뀐다
np.transpose(a)

array([[0, 2, 4],
       [1, 3, 5]])

In [296]:
a = np.array([1,2,3,4])
b = np.array([1,3,4,2])
a == b

array([ True, False, False, False])

In [297]:
a > 2

array([False, False,  True,  True])

In [304]:
#sort
a = np.array([1,3,4,2])

np.sort(a)
print(a)

a.sort()
print(a)

[1 3 4 2]
[1 2 3 4]


In [309]:
a[ : :-1]

array([4, 3, 2, 1])

In [312]:
a = np.array([[2,1,3], [0,7,4], [5,3,2]])
a

array([[2, 1, 3],
       [0, 7, 4],
       [5, 3, 2]])

In [317]:
#각 열별로 비교
np.sort(a, axis = 0)

array([[0, 1, 2],
       [2, 3, 3],
       [5, 7, 4]])

In [321]:
#각 행별로 배교
np.sort(a, axis = 1)

array([[1, 2, 3],
       [0, 4, 7],
       [2, 3, 5]])

In [323]:
a = np.arange(8)*10
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [325]:
#indexing
a[[1,2,-3]]

array([10, 20, 50])

In [326]:
#mask
mask = [False, True, True, False, False, True, False, False]
a[mask]

array([10, 20, 50])

In [153]:
mask = np.array([0,1,1,0,0,1,0,0], dtype = bool)
a[mask]

array([10, 20, 50])

In [327]:
#2차원 fancy indexing
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [328]:
a[[0,1,2,3], [1,2,3,4]]

array([ 1,  7, 13, 19])

In [332]:
#Universal Functions

In [340]:
a = np.array([[1,2,3],[4,5,6]])

In [166]:
np.sum(a)

21

In [331]:
#열끼리 더한다
np.sum(a, axis = 0)

array([5, 7, 9])

In [330]:
#행끼리 더한다
np.sum(a, axis = 1)

array([ 6, 15])

In [333]:
#각 열의 최솟값
np.min(a, axis = 0)

array([1, 2, 3])

In [335]:
#각 행의 최댓값
np.max(a, axis = 1)

array([3, 6])

In [337]:
#1차원으로 바꾼뒤 최솟값의 인덱스를 리턴
np.argmin(a)

0

In [343]:
#1차원으로 바꾼뒤 최댓값의 인덱스를 리턴
np.argmax(a)

5

In [345]:
a = np.arange(-15,15).reshape(5,6)**2
a

array([[225, 196, 169, 144, 121, 100],
       [ 81,  64,  49,  36,  25,  16],
       [  9,   4,   1,   0,   1,   4],
       [  9,  16,  25,  36,  49,  64],
       [ 81, 100, 121, 144, 169, 196]])

In [346]:
#각 열별로 최댓값
np.max(a, axis = 0)

array([225, 196, 169, 144, 169, 196])

In [347]:
#각 행별로 최댓값
np.max(a, axis = 1)

array([225,  81,   9,  64, 196])

In [350]:
#각 열의 평균
np.mean(a, axis = 0)

array([81., 76., 73., 72., 73., 76.])

In [351]:
#각 행의 평균
np.mean(a, axis = 1)

array([159.16666667,  45.16666667,   3.16666667,  33.16666667,
       135.16666667])

In [352]:
#where
np.where(a<10)

(array([2, 2, 2, 2, 2, 2, 3], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 0], dtype=int64))

In [353]:
np.where(a>10, 'pass', 'fail')

array([['pass', 'pass', 'pass', 'pass', 'pass', 'pass'],
       ['pass', 'pass', 'pass', 'pass', 'pass', 'pass'],
       ['fail', 'fail', 'fail', 'fail', 'fail', 'fail'],
       ['fail', 'pass', 'pass', 'pass', 'pass', 'pass'],
       ['pass', 'pass', 'pass', 'pass', 'pass', 'pass']], dtype='<U4')

In [354]:
a[np.where(a<10)]

array([9, 4, 1, 0, 1, 4, 9])