# 데이터 변형

## 함수, 매핑을 이용해서 데이터 변형하기

In [5]:
import pandas as pd

In [2]:
data = pd.DataFrame({'food' : ['bacon', 'pulled pork', 'bacon',
                               'Pastrami', 'corned beef', 'Bacon',
                               'pastrami', 'honey ham', 'nova lox'],
                     'ounces' : [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [3]:
meat_to_animal = {
    'bacon':'pig',
    'pulled pork':'pig',
    'pastrami':'cow',
    'corned beef':'cow',
    'honey ham':'pig',
    'nova lox':'salmon'
}
meat_to_animal

{'bacon': 'pig',
 'pulled pork': 'pig',
 'pastrami': 'cow',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon'}

In [121]:
#벡터화된 문자열 메소드 str.___()
data['animal'] = data['food'].str.lower().map(meat_to_animal)

In [122]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [6]:
import numpy as np

In [245]:
data = pd.DataFrame(np.arange(12).reshape(3, 4),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [246]:
f = lambda x: x[:4].upper()
f('abcdef')

'ABCD'

In [249]:
data.index = data.index.map(f)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [250]:
data.columns = data.columns.map(f)
data

ONE  TWO  THRE  FOUR
OHIO    0    1     2     3
COLO    4    5     6     7
NEW     8    9    10    11

In [251]:
data.rename(index = str.title, columns = str.lower)

one  two  thre  four
Ohio    0    1     2     3
Colo    4    5     6     7
New     8    9    10    11

## 개별화와 양자화

In [6]:
ages = [22, 25, 40, 45, 56, 82]
bins = [20, 40, 60, 100]

In [7]:
#기본은 left = False num1 < x <= num2, right = False 하면 num1 <= x < num2
cats = pd.cut(ages,bins)
cats

[(20, 40], (20, 40], (20, 40], (40, 60], (40, 60], (60, 100]]
Categories (3, interval[int64, right]): [(20, 40] < (40, 60] < (60, 100]]

In [354]:
cats.codes

array([0, 0, 0, 1, 1, 2], dtype=int8)

In [355]:
cats.value_counts()

(20, 40]     3
(40, 60]     2
(60, 100]    1
dtype: int64

In [356]:
group_names = ['YoungAdult', 'MiddleAged', 'Senior'] 

In [357]:
pd.cut(ages, bins, labels = group_names)

['YoungAdult', 'YoungAdult', 'YoungAdult', 'MiddleAged', 'MiddleAged', 'Senior']
Categories (3, object): ['YoungAdult' < 'MiddleAged' < 'Senior']

In [362]:
pd.cut(ages, 4)

[(21.94, 37.0], (21.94, 37.0], (37.0, 52.0], (37.0, 52.0], (52.0, 67.0], (67.0, 82.0]]
Categories (4, interval[float64, right]): [(21.94, 37.0] < (37.0, 52.0] < (52.0, 67.0] < (67.0, 82.0]]

In [363]:
pd.qcut(ages,4)

[(21.999, 28.75], (21.999, 28.75], (28.75, 42.5], (42.5, 53.25], (53.25, 82.0], (53.25, 82.0]]
Categories (4, interval[float64, right]): [(21.999, 28.75] < (28.75, 42.5] < (42.5, 53.25] < (53.25, 82.0]]

In [364]:
pd.qcut(ages,4).value_counts()

(21.999, 28.75]    2
(28.75, 42.5]      1
(42.5, 53.25]      1
(53.25, 82.0]      2
dtype: int64

## 치환과 임의 샘플링

In [366]:
np.random.permutation(10)

array([9, 5, 0, 3, 6, 4, 1, 7, 2, 8])

In [367]:
import pydataset

In [368]:
mpg = pydataset.data('mpg')
mpg

manufacturer   model  displ  year  cyl       trans drv  cty  hwy fl  \
1           audi      a4    1.8  1999    4    auto(l5)   f   18   29  p   
2           audi      a4    1.8  1999    4  manual(m5)   f   21   29  p   
3           audi      a4    2.0  2008    4  manual(m6)   f   20   31  p   
4           audi      a4    2.0  2008    4    auto(av)   f   21   30  p   
5           audi      a4    2.8  1999    6    auto(l5)   f   16   26  p   
..           ...     ...    ...   ...  ...         ...  ..  ...  ... ..   
230   volkswagen  passat    2.0  2008    4    auto(s6)   f   19   28  p   
231   volkswagen  passat    2.0  2008    4  manual(m6)   f   21   29  p   
232   volkswagen  passat    2.8  1999    6    auto(l5)   f   16   26  p   
233   volkswagen  passat    2.8  1999    6  manual(m5)   f   18   26  p   
234   volkswagen  passat    3.6  2008    6    auto(s6)   f   17   26  p   

       class  
1    compact  
2    compact  
3    compact  
4    compact  
5    compact  
..       ...  
230  midsize  
231  midsize  
232  midsize  
233  midsize  
234  midsize  

[234 rows x 11 columns]

In [371]:
si = np.random.permutation(len(mpg))
si

array([ 24,  28, 132, 158,   9, 226, 105,  74,  20, 156, 193,  29, 201,
       123, 178,  55, 148,  71,  93,  96, 160, 115,  21,  66,  44,  12,
       231, 216, 186, 131, 118, 133,  73, 163, 195, 175,  33, 218, 212,
       127,  86, 171, 138,  94,  13, 116, 143, 225, 228,   2, 102, 109,
        35,  72, 112, 126, 161, 135, 103,  39,  52, 170, 168, 184, 210,
        81, 153,  79,  95, 141,   3,  75,  80, 107,  22, 229, 155, 130,
        58, 139,  17,   1, 220,  26, 219,  49, 137, 176, 124,  14, 187,
       227,  11, 185,  64, 194, 230,  18, 121,  68,   5, 224,  43, 177,
        77, 232,  54,  31,  63,  56, 119,  23, 211, 114, 162,   7, 136,
        32, 192, 190, 217, 208,  67,  89, 189, 205, 164, 174,  57,  51,
        19, 221, 188, 106, 169, 202,  98,  46, 183,  30, 222,  15, 196,
        69, 204, 213,  36, 215, 209, 125,  40, 172, 191, 113,  34,  61,
       120, 128, 165, 150,  85, 142,  16, 233,  62,   6, 145, 167, 122,
        25, 108,  48,  42,  37,  82, 111, 214, 166,  41,  91, 22

In [380]:
mpg1 = mpg.take(si)
mpg1

manufacturer            model  displ  year  cyl       trans drv  cty  hwy  \
25     chevrolet         corvette    5.7  1999    8    auto(l4)   r   15   23   
29     chevrolet  k1500 tahoe 4wd    5.3  2008    8    auto(l4)   4   14   19   
133   land rover      range rover    4.4  2008    8    auto(s6)   4   12   18   
159      pontiac       grand prix    5.3  2008    8    auto(s4)   f   16   25   
10          audi       a4 quattro    2.0  2008    4  manual(m6)   4   20   28   
..           ...              ...    ...   ...  ...         ...  ..  ...  ...   
98          ford          mustang    4.6  2008    8    auto(l5)   r   15   22   
180       toyota            camry    2.2  1999    4  manual(m5)   f   21   29   
198       toyota          corolla    1.8  2008    4    auto(l4)   f   26   35   
118      hyundai          tiburon    2.0  2008    4  manual(m5)   f   20   28   
88          ford  f150 pickup 4wd    4.6  2008    8    auto(l4)   4   13   17   

    fl       class  
25   p     2seater  
29   r         suv  
133  r         suv  
159  p     midsize  
10   p     compact  
..  ..         ...  
98   r  subcompact  
180  r     midsize  
198  r     compact  
118  r  subcompact  
88   r      pickup  

[234 rows x 11 columns]

In [385]:
#아무거나 10개
mpg2 = mpg.sample(10)
mpg2

manufacturer                model  displ  year  cyl       trans drv  cty  \
65         dodge  ram 1500 pickup 4wd    4.7  2008    8  manual(m6)   4   12   
214   volkswagen                jetta    2.0  1999    4  manual(m5)   f   21   
32     chevrolet      k1500 tahoe 4wd    6.5  1999    8    auto(l4)   4   14   
1           audi                   a4    1.8  1999    4    auto(l5)   f   18   
66         dodge  ram 1500 pickup 4wd    4.7  2008    8    auto(l5)   4    9   
114      hyundai               sonata    2.5  1999    6  manual(m5)   f   18   
15          audi           a4 quattro    3.1  2008    6  manual(m6)   4   15   
161       subaru         forester awd    2.5  1999    4    auto(l4)   4   18   
54         dodge    dakota pickup 4wd    4.7  2008    8    auto(l5)   4   14   
61         dodge          durango 4wd    4.7  2008    8    auto(l5)   4   13   

     hwy fl    class  
65    16  r   pickup  
214   29  r  compact  
32    17  d      suv  
1     29  p  compact  
66    12  e   pickup  
114   26  r  midsize  
15    25  p  compact  
161   24  r      suv  
54    19  r   pickup  
61    17  r      suv

In [386]:
#아무거나 10%
mpg3 = mpg.sample(frac = .1)
mpg3

manufacturer                model  displ  year  cyl       trans drv  cty  \
168       subaru          impreza awd    2.5  1999    4  manual(m5)   4   19   
94          ford              mustang    4.0  2008    6    auto(l5)   r   16   
205       toyota    toyota tacoma 4wd    3.4  1999    6    auto(l4)   4   15   
44         dodge          caravan 2wd    3.3  2008    6    auto(l4)   f   11   
33     chevrolet               malibu    2.4  1999    4    auto(l4)   f   19   
42         dodge          caravan 2wd    3.3  2008    6    auto(l4)   f   17   
73         dodge  ram 1500 pickup 4wd    5.7  2008    8    auto(l5)   4   13   
79          ford         explorer 4wd    4.0  1999    6  manual(m5)   4   15   
92          ford              mustang    3.8  1999    6    auto(l4)   r   18   
72         dodge  ram 1500 pickup 4wd    5.2  1999    8  manual(m5)   4   11   
194       toyota              corolla    1.8  1999    4    auto(l3)   f   24   
176       toyota          4runner 4wd    3.4  1999    6    auto(l4)   4   15   
163       subaru         forester awd    2.5  2008    4  manual(m5)   4   19   
162       subaru         forester awd    2.5  2008    4  manual(m5)   4   20   
23     chevrolet   c1500 suburban 2wd    6.0  2008    8    auto(l4)   r   12   
36     chevrolet               malibu    3.5  2008    6    auto(l4)   f   18   
85          ford      f150 pickup 4wd    4.2  1999    6  manual(m5)   4   14   
196       toyota              corolla    1.8  1999    4  manual(m5)   f   26   
183       toyota                camry    2.4  2008    4    auto(l5)   f   21   
229   volkswagen               passat    1.8  1999    4    auto(l5)   f   18   
69         dodge  ram 1500 pickup 4wd    4.7  2008    8  manual(m6)   4   12   
38         dodge          caravan 2wd    2.4  1999    4    auto(l3)   f   18   
121      hyundai              tiburon    2.7  2008    6  manual(m6)   f   16   

     hwy fl       class  
168   26  r  subcompact  
94    24  r  subcompact  
205   19  r      pickup  
44    17  e     minivan  
33    27  r     midsize  
42    24  r     minivan  
73    17  r      pickup  
79    19  r         suv  
92    25  r  subcompact  
72    16  r      pickup  
194   30  r     compact  
176   19  r         suv  
163   25  p         suv  
162   27  r         suv  
23    17  r         suv  
36    29  r     midsize  
85    17  r      pickup  
196   35  r     compact  
183   31  r     midsize  
229   29  p     midsize  
69    16  r      pickup  
38    24  r     minivan  
121   24  r  subcompact

## 표시자 변수 계산하기

In [7]:
df = pd.DataFrame({'key': ['a','a','b','c','d','d'],
                   'data1': range(6)}) 

In [8]:
df

key  data1
0   a      0
1   a      1
2   b      2
3   c      3
4   d      4
5   d      5

In [9]:
pd.get_dummies(df['key'])

a  b  c  d
0  1  0  0  0
1  1  0  0  0
2  0  1  0  0
3  0  0  1  0
4  0  0  0  1
5  0  0  0  1

# 데이터 준비하기

## unstack()/stack()

In [13]:
data = pd.Series(np.random.randn(9),
                 index=[['a','a','a','b','b','c','c','d','d'],
                        [1, 2, 3, 1, 3, 1, 2, 2, 3]])
data

a  1   -1.473550
   2    1.971101
   3   -0.057802
b  1   -1.336378
   3    0.980453
c  1    1.278206
   2    1.766437
d  2   -0.328400
   3    0.053121
dtype: float64

In [10]:
data.unstack()

1         2         3
a -0.879650 -0.534176  0.133075
b  2.186686       NaN -0.589608
c -0.789694  1.001045       NaN
d       NaN  0.892070  1.778237

In [16]:
data.unstack().stack()

a  1   -1.473550
   2    1.971101
   3   -0.057802
b  1   -1.336378
   3    0.980453
c  1    1.278206
   2    1.766437
d  2   -0.328400
   3    0.053121
dtype: float64

In [94]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                     index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                     columns=[['Ohio', 'Ohio', 'Colorado'],
                              ['Green', 'Red', 'Green']])
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [95]:
frame.unstack()

Ohio            Colorado    
  Green    Red        Green    
      1  2   1   2        1   2
a     0  3   1   4        2   5
b     6  9   7  10        8  11

In [100]:
frame.stack()

Colorado  Ohio
a 1 Green       2.0     0
    Red         NaN     1
  2 Green       5.0     3
    Red         NaN     4
b 1 Green       8.0     6
    Red         NaN     7
  2 Green      11.0     9
    Red         NaN    10

In [17]:
frame = pd.DataFrame({'a': range(7), 'b': range(7, 0, -1),
                      'c': ['one', 'one', 'one', 'two', 'two',
                            'two', 'two'],
                      'd': [0, 1, 2, 0, 1, 2, 3]}) 

In [18]:
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [19]:
frame = frame.set_index('c')
frame

a  b  d
c           
one  0  7  0
one  1  6  1
one  2  5  2
two  3  4  0
two  4  3  1
two  5  2  2
two  6  1  3

In [20]:
frame = frame.reset_index()
frame

c  a  b  d
0  one  0  7  0
1  one  1  6  1
2  one  2  5  2
3  two  3  4  0
4  two  4  3  1
5  two  5  2  2
6  two  6  1  3

In [21]:
frame = frame.set_index(['a','b'])
frame

c  d
a b        
0 7  one  0
1 6  one  1
2 5  one  2
3 4  two  0
4 3  two  1
5 2  two  2
6 1  two  3

## merge

In [28]:
df1 = pd.DataFrame({'key': ['b','b','a','c','a','a','b'],
                   'data1': range(7)})
df2 = pd.DataFrame({'key': ['a','b','d'],
                   'data2': range(3)})

In [29]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [30]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [31]:
pd.merge(df1, df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [33]:
#모든 데이터 살리기
pd.merge(df1,df2, how = 'outer')

key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

In [34]:
pd.merge(df1,df2, how = 'outer', indicator=True)

key  data1  data2      _merge
0   b    0.0    1.0        both
1   b    1.0    1.0        both
2   b    6.0    1.0        both
3   a    2.0    0.0        both
4   a    4.0    0.0        both
5   a    5.0    0.0        both
6   c    3.0    NaN   left_only
7   d    NaN    2.0  right_only

In [35]:
#왼쪽 데이터만 살리기
pd.merge(df1,df2, how = 'left')

key  data1  data2
0   b      0    1.0
1   b      1    1.0
2   a      2    0.0
3   c      3    NaN
4   a      4    0.0
5   a      5    0.0
6   b      6    1.0

In [36]:
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                    'data1': range(7)})
df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'],
                    'data2': range(3)}) 

In [37]:
df3

lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [38]:
df4

rkey  data2
0    a      0
1    b      1
2    d      2

In [74]:
pd.merge(df3,df4, left_on = 'lkey', right_on = 'rkey')

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

In [84]:
pd.merge(df3,df4, left_on = 'lkey', right_on = 'rkey', how = 'outer', indicator=True)

lkey  data1 rkey  data2      _merge
0    b    0.0    b    1.0        both
1    b    1.0    b    1.0        both
2    b    6.0    b    1.0        both
3    a    2.0    a    0.0        both
4    a    4.0    a    0.0        both
5    a    5.0    a    0.0        both
6    c    3.0  NaN    NaN   left_only
7  NaN    NaN    d    2.0  right_only

In [64]:
left = pd.DataFrame({'key1': ['foo', 'foo', 'bar'],
                     'key2': ['one', 'two', 'one'],
                     'lval': [1, 2, 3]})
right = pd.DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],
                      'key2': ['one', 'one', 'one', 'two'],
                      'rval': [4, 5, 6, 7]}) 

In [65]:
left

key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [66]:
right

key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [67]:
pd.merge(left,right)

key1 key2  lval  rval
0  foo  one     1     4
1  foo  one     1     5
2  bar  one     3     6

In [87]:
pd.merge(left, right, on='key1')

key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [76]:
left1 = pd.DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'],
                      'value': range(6)})
right1 = pd.DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])

In [77]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [78]:
right1 

group_val
a        3.5
b        7.0

In [89]:
pd.merge(left1,right1, left_on = 'key', right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [90]:
left1 = left1.set_index('key')
left1

value
key       
a        0
b        1
a        2
a        3
b        4
c        5

In [94]:
pd.merge(left1, right1, left_index = True, right_index = True)

value  group_val
a      0        3.5
a      2        3.5
a      3        3.5
b      1        7.0
b      4        7.0

## concat

In [95]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
arr1 = arr.copy()

In [97]:
np.concatenate([arr,arr1])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
np.concatenate([arr,arr1], axis = 1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [100]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=['a', 'b', 'c'],
                   columns=['one', 'two'])
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=['a', 'c'],
                   columns=['three', 'four']) 

In [101]:
df1

one  two
a    0    1
b    2    3
c    4    5

In [102]:
df2

three  four
a      5     6
c      7     8

In [206]:
pd.concat([df1,df2])

one  two  three  four
a  0.0  1.0    NaN   NaN
b  2.0  3.0    NaN   NaN
c  4.0  5.0    NaN   NaN
a  NaN  NaN    5.0   6.0
c  NaN  NaN    7.0   8.0

In [207]:
pd.concat([df1,df2], axis = 1)

one  two  three  four
a    0    1    5.0   6.0
b    2    3    NaN   NaN
c    4    5    7.0   8.0

In [208]:
df3 = df1.loc[['c']]
df3

one  two
c    4    5

In [209]:
pd.concat([df1,df3])

one  two
a    0    1
b    2    3
c    4    5
c    4    5

## melt

In [37]:
df = pd.DataFrame({'key': ['foo', 'bar', 'baz'],
                   'A': [1, 2, 3],
                   'B': [4, 5, 6],
                   'C': [7, 8, 9]})
df 

key  A  B  C
0  foo  1  4  7
1  bar  2  5  8
2  baz  3  6  9

In [38]:
df.melt()

variable value
0       key   foo
1       key   bar
2       key   baz
3         A     1
4         A     2
5         A     3
6         B     4
7         B     5
8         B     6
9         C     7
10        C     8
11        C     9

In [39]:
df.melt(id_vars=['A','B'])

A  B variable value
0  1  4      key   foo
1  2  5      key   bar
2  3  6      key   baz
3  1  4        C     7
4  2  5        C     8
5  3  6        C     9

In [40]:
df.melt(value_vars=['A','B'])

variable  value
0        A      1
1        A      2
2        A      3
3        B      4
4        B      5
5        B      6

In [41]:
df = df.melt(id_vars=['key'], value_vars=['A','B','C'])
df

key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6
6  foo        C      7
7  bar        C      8
8  baz        C      9

## pivot

In [42]:
df

key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6
6  foo        C      7
7  bar        C      8
8  baz        C      9

In [43]:
df.pivot(index = 'key', columns = 'variable', values = 'value')

variable  A  B  C
key              
bar       2  5  8
baz       3  6  9
foo       1  4  7

In [44]:
data = pd.read_csv("https://raw.githubusercontent.com/wesm/pydata-book/3rd-edition/examples/macrodata.csv")
data

year  quarter    realgdp  realcons   realinv  realgovt  realdpi      cpi  \
0    1959        1   2710.349    1707.4   286.898   470.045   1886.9   28.980   
1    1959        2   2778.801    1733.7   310.859   481.301   1919.7   29.150   
2    1959        3   2775.488    1751.8   289.226   491.260   1916.4   29.350   
3    1959        4   2785.204    1753.7   299.356   484.052   1931.3   29.370   
4    1960        1   2847.699    1770.5   331.722   462.199   1955.5   29.540   
..    ...      ...        ...       ...       ...       ...      ...      ...   
198  2008        3  13324.600    9267.7  1990.693   991.551   9838.3  216.889   
199  2008        4  13141.920    9195.3  1857.661  1007.273   9920.4  212.174   
200  2009        1  12925.410    9209.2  1558.494   996.287   9926.4  212.671   
201  2009        2  12901.504    9189.0  1456.678  1023.528  10077.5  214.469   
202  2009        3  12990.341    9256.0  1486.398  1044.088  10040.6  216.385   

         m1  tbilrate  unemp      pop  infl  realint  
0     139.7      2.82    5.8  177.146  0.00     0.00  
1     141.7      3.08    5.1  177.830  2.34     0.74  
2     140.5      3.82    5.3  178.657  2.74     1.09  
3     140.0      4.33    5.6  179.386  0.27     4.06  
4     139.6      3.50    5.2  180.007  2.31     1.19  
..      ...       ...    ...      ...   ...      ...  
198  1474.7      1.17    6.0  305.270 -3.16     4.33  
199  1576.5      0.12    6.9  305.952 -8.79     8.91  
200  1592.8      0.22    8.1  306.547  0.94    -0.71  
201  1653.6      0.18    9.2  307.226  3.37    -3.19  
202  1673.9      0.12    9.6  308.013  3.56    -3.44  

[203 rows x 14 columns]

In [45]:
periods = pd.PeriodIndex(year=data.year, quarter=data.quarter, name='date')
columns = pd.Index(['realgdp', 'infl', 'unemp'], name='item')
data = data.reindex(columns=columns)
data.index = periods.to_timestamp('D', 'end')
ldata = data.stack().reset_index().rename(columns={0: 'value'}) 

In [82]:
ldata

date     item      value
0   1959-03-31 23:59:59.999999999  realgdp   2710.349
1   1959-03-31 23:59:59.999999999     infl      0.000
2   1959-03-31 23:59:59.999999999    unemp      5.800
3   1959-06-30 23:59:59.999999999  realgdp   2778.801
4   1959-06-30 23:59:59.999999999     infl      2.340
..                            ...      ...        ...
604 2009-06-30 23:59:59.999999999     infl      3.370
605 2009-06-30 23:59:59.999999999    unemp      9.200
606 2009-09-30 23:59:59.999999999  realgdp  12990.341
607 2009-09-30 23:59:59.999999999     infl      3.560
608 2009-09-30 23:59:59.999999999    unemp      9.600

[609 rows x 3 columns]

In [84]:
pivoted = ldata.pivot(index = 'date', columns = 'item', values = 'value')
pivoted

item                           infl    realgdp  unemp
date                                                 
1959-03-31 23:59:59.999999999  0.00   2710.349    5.8
1959-06-30 23:59:59.999999999  2.34   2778.801    5.1
1959-09-30 23:59:59.999999999  2.74   2775.488    5.3
1959-12-31 23:59:59.999999999  0.27   2785.204    5.6
1960-03-31 23:59:59.999999999  2.31   2847.699    5.2
...                             ...        ...    ...
2008-09-30 23:59:59.999999999 -3.16  13324.600    6.0
2008-12-31 23:59:59.999999999 -8.79  13141.920    6.9
2009-03-31 23:59:59.999999999  0.94  12925.410    8.1
2009-06-30 23:59:59.999999999  3.37  12901.504    9.2
2009-09-30 23:59:59.999999999  3.56  12990.341    9.6

[203 rows x 3 columns]

In [87]:
ldata['value2'] = np.random.randn(len(ldata))
ldata

date     item      value    value2
0   1959-03-31 23:59:59.999999999  realgdp   2710.349 -0.144237
1   1959-03-31 23:59:59.999999999     infl      0.000  2.250537
2   1959-03-31 23:59:59.999999999    unemp      5.800  0.470732
3   1959-06-30 23:59:59.999999999  realgdp   2778.801 -0.335045
4   1959-06-30 23:59:59.999999999     infl      2.340 -0.082943
..                            ...      ...        ...       ...
604 2009-06-30 23:59:59.999999999     infl      3.370  1.310149
605 2009-06-30 23:59:59.999999999    unemp      9.200  1.428990
606 2009-09-30 23:59:59.999999999  realgdp  12990.341  1.374057
607 2009-09-30 23:59:59.999999999     infl      3.560  2.350707
608 2009-09-30 23:59:59.999999999    unemp      9.600  1.255322

[609 rows x 4 columns]

In [91]:
ldata.pivot(index = 'date', columns = 'item', values = ['value', 'value2'])

value                     value2            \
item                           infl    realgdp unemp      infl   realgdp   
date                                                                       
1959-03-31 23:59:59.999999999  0.00   2710.349   5.8  2.250537 -0.144237   
1959-06-30 23:59:59.999999999  2.34   2778.801   5.1 -0.082943 -0.335045   
1959-09-30 23:59:59.999999999  2.74   2775.488   5.3  0.533158 -0.312693   
1959-12-31 23:59:59.999999999  0.27   2785.204   5.6  0.427391  1.226179   
1960-03-31 23:59:59.999999999  2.31   2847.699   5.2  0.347473 -0.116532   
...                             ...        ...   ...       ...       ...   
2008-09-30 23:59:59.999999999 -3.16  13324.600   6.0  2.589208 -0.369550   
2008-12-31 23:59:59.999999999 -8.79  13141.920   6.9 -0.531061  0.866125   
2009-03-31 23:59:59.999999999  0.94  12925.410   8.1  0.106366 -1.777775   
2009-06-30 23:59:59.999999999  3.37  12901.504   9.2  1.310149 -0.816045   
2009-09-30 23:59:59.999999999  3.56  12990.341   9.6  2.350707  1.374057   

                                         
item                              unemp  
date                                     
1959-03-31 23:59:59.999999999  0.470732  
1959-06-30 23:59:59.999999999 -0.105841  
1959-09-30 23:59:59.999999999  1.534296  
1959-12-31 23:59:59.999999999  1.041735  
1960-03-31 23:59:59.999999999  1.953702  
...                                 ...  
2008-09-30 23:59:59.999999999 -0.754010  
2008-12-31 23:59:59.999999999 -1.433058  
2009-03-31 23:59:59.999999999 -0.358088  
2009-06-30 23:59:59.999999999  1.428990  
2009-09-30 23:59:59.999999999  1.255322  

[203 rows x 6 columns]

In [113]:
#unstack을 이용한 방법 (위와 같다)
ldata.set_index(['date','item'])

value    value2
date                          item                        
1959-03-31 23:59:59.999999999 realgdp   2710.349 -0.144237
                              infl         0.000  2.250537
                              unemp        5.800  0.470732
1959-06-30 23:59:59.999999999 realgdp   2778.801 -0.335045
                              infl         2.340 -0.082943
...                                          ...       ...
2009-06-30 23:59:59.999999999 infl         3.370  1.310149
                              unemp        9.200  1.428990
2009-09-30 23:59:59.999999999 realgdp  12990.341  1.374057
                              infl         3.560  2.350707
                              unemp        9.600  1.255322

[609 rows x 2 columns]

In [114]:
ldata.set_index(['date','item']).unstack()

value                     value2            \
item                           infl    realgdp unemp      infl   realgdp   
date                                                                       
1959-03-31 23:59:59.999999999  0.00   2710.349   5.8  2.250537 -0.144237   
1959-06-30 23:59:59.999999999  2.34   2778.801   5.1 -0.082943 -0.335045   
1959-09-30 23:59:59.999999999  2.74   2775.488   5.3  0.533158 -0.312693   
1959-12-31 23:59:59.999999999  0.27   2785.204   5.6  0.427391  1.226179   
1960-03-31 23:59:59.999999999  2.31   2847.699   5.2  0.347473 -0.116532   
...                             ...        ...   ...       ...       ...   
2008-09-30 23:59:59.999999999 -3.16  13324.600   6.0  2.589208 -0.369550   
2008-12-31 23:59:59.999999999 -8.79  13141.920   6.9 -0.531061  0.866125   
2009-03-31 23:59:59.999999999  0.94  12925.410   8.1  0.106366 -1.777775   
2009-06-30 23:59:59.999999999  3.37  12901.504   9.2  1.310149 -0.816045   
2009-09-30 23:59:59.999999999  3.56  12990.341   9.6  2.350707  1.374057   

                                         
item                              unemp  
date                                     
1959-03-31 23:59:59.999999999  0.470732  
1959-06-30 23:59:59.999999999 -0.105841  
1959-09-30 23:59:59.999999999  1.534296  
1959-12-31 23:59:59.999999999  1.041735  
1960-03-31 23:59:59.999999999  1.953702  
...                                 ...  
2008-09-30 23:59:59.999999999 -0.754010  
2008-12-31 23:59:59.999999999 -1.433058  
2009-03-31 23:59:59.999999999 -0.358088  
2009-06-30 23:59:59.999999999  1.428990  
2009-09-30 23:59:59.999999999  1.255322  

[203 rows x 6 columns]